GNUSTEP_MAKEFILES = /usr/share/GNUstep/Makefiles

ADDITIONAL_FLAGS += -Wall -std=c99
include $(GNUSTEP_MAKEFILES)/common.make
TOOL_NAME = app
app_OBJC_FILES = main.m
include $(GNUSTEP_MAKEFILES)/tool.make
